# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45a22f689e44fc6c79f44d4d88e1c3b94e64f5509b8fb782b78c406512308440216be71bcf06c62e9e6bd9d349dd0b2a37a9390be244a357c4ca2fb6745b86e3

test:
  secret_key_base: 23efcc47b26732d5d2de45884e639795dece0877ccc7dcada11ef31eee283240eb7f7c33d4fe1dbe57581d92b9b786e6fca5d9247196d215e2faa3dc4b033f5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
